<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="2" tests="12" time="0.049" timestamp="2021-02-03T09:51:22.005395" hostname="periscopai"><testcase classname="tmp.test_suite_1" name="test_case_1" time="0.000" /><testcase classname="tmp.test_suite_1.TestSuiteC1" name="test_case_2" time="0.000" /><testcase classname="tmp.test_suite_1.TestSuiteC1" name="test_case_3" time="0.000" /><testcase classname="tmp.test_suite_2" name="test_case_4" time="0.000" /><testcase classname="tmp.test_suite_2.TestSuiteC2" name="test_case_5" time="0.000" /><testcase classname="tmp.test_suite_2.TestSuiteC2" name="test_case_6" time="0.000" /><testcase classname="tmp.py_special_cases.test_suite_4" name="test_fail" time="0.000"><failure message="AssertionError: Failure!&#10;assert 0">def test_fail():
        sys.stdout.write(f"stdout {test_fail.__name__}")
        sys.stdout.write(f"stderr {test_fail.__name__}")
&gt;       assert 0, "Failure!"
E       AssertionError: Failure!
E       assert 0

tmp/py_special_cases/test_suite_4.py:7: AssertionError</failure></testcase><testcase classname="tmp.py_special_cases.test_suite_4" name="test_xfail" time="0.000"><skipped type="pytest.xfail" message="reason for xfailing" /></testcase><testcase classname="tmp.py_special_cases.test_suite_4" name="test_skip" time="0.000"><skipped type="pytest.skip" message="unconditional skip">/home/laurent/github/laurent/testspace-colab/tmp/py_special_cases/test_suite_4.py:16: unconditional skip</skipped></testcase><testcase classname="tmp.pyfoldler_1.test_suite_3" name="test_case_7" time="0.000" /><testcase classname="tmp.pyfoldler_1.test_suite_3.TestSuiteC3" name="test_case_8" time="0.000" /><testcase classname="tmp.pyfoldler_1.test_suite_3.TestSuiteC3" name="test_case_9" time="0.000" /></testsuite></testsuites>